_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.1
        t:
            "1":
                - 1
                - 54
                - 55
            "2":
                - 1
                - 54
                - 55
            "3":
                - 1
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.1
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
base_lr:
    value: "1e-4"
epochs:
    value: 10
loss:
    value: MSE
max_lr:
    value: "1e-3"
mode:
    value: triangular
optimizer:
    value: Adam
scheduler:
    value: CyclicLR
