experiment:
  batch_size: 32
  num_workers: 4
  quick_test: true

variables:
  input:
    precip: pr
    temp: tas
  target:
    precip: RhiresD
    temp: TabsD

preprocessing:
  nan_to_num: true
  nan_value : 0.0

split:
  method: "by_decade"
  seed: 42
  train_frac: 0.7
  val_frac: 0.2
  #Above code Will be later customised for spatial cross val ewtcc

train:
  num_epochs: 10
  checkpoint_path: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling/checkpoints/best_model_Cyclical_LR_100samples_20epochs.pth
  in_channels: 2
  out_channels: 2
  optimizer: "Adam"
  loss_fn: "MSE"
  scheduler: "CyclicLR"
  scheduler_mode: "triangular"
  base_lr: 1e-4
  max_lr: 1e-3

  step_size_up: 208
  #How was step size chosen? Numer of iterations(training batches) per epoch= len(training_set)/batch_size
  #So following from above, step size up= Number iter per epoch//2
  wandb_project: "UNet_Deterministic_YAML_check"
  wandb_run_name: "CLR_experiment"

# Placeholder for the paths in the untracked .paths.yaml file
data: {}
